In [3]:
import torch

In [9]:
x = torch.arange(12, dtype=torch.float32)
print("x = {}".format(x))
print("numel = {}".format(x.numel()))

print("shape = {}".format(x.shape))
print("reshaped to = {}".format(x.reshape(3,-1).shape))

print("ones = {}".format(torch.ones((1,2))))

x = tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
numel = 12
shape = torch.Size([12])
reshaped to = torch.Size([3, 4])
ones = tensor([[1., 1.]])


In [17]:
y = x[-1], x[1:3]
print("tuple of indexed values = {}".format(y))
print("x:y will take values from x to y-1 inclusive")

tuple of indexed values = (tensor(11.), tensor([1., 2.]))
x:y will take values from x to y-1 inclusive


In [19]:
z = torch.tensor([[ 0.,  1.,  2.,  3.],
                  [ 4.,  5., 17.,  7.],
                  [ 8.,  9., 10., 11.]])
print(z[:2, :])

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.]])


In [20]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [21]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X,Y), dim=0), torch.cat((X,Y), dim=1) 

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))