In [14]:
### Visualization
import os
import open3d as o3d
import numpy as np
from open3d import JVisualizer
import ipywidgets as widgets

camera_location = np.array([0.0, 0.0, 0.0])
coord = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.5, origin=camera_location)

print("Load a ply point cloud, print it, and render it")
pcd = o3d.io.read_point_cloud("../../../Open3D/examples/test_data/fragment.ply")

if (np.asarray(pcd.points).size == 0):
    print("Point cloud file needs to be pointed to Open3d's repository")
else:
    print(pcd)
    print(np.asarray(pcd.points))
    print(np.asarray(pcd.colors))

# visualization
o3d.visualization.draw_geometries([coord, pcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024],
                                  mesh_show_back_face=True,mesh_show_wireframe=True)

Load a ply point cloud, print it, and render it
PointCloud with 196133 points.
[[0.65234375 0.84686458 2.37890625]
 [0.65234375 0.83984375 2.38430572]
 [0.66737998 0.83984375 2.37890625]
 ...
 [2.00839925 2.39453125 1.88671875]
 [2.00390625 2.39488506 1.88671875]
 [2.00390625 2.39453125 1.88793314]]
[[0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 ...
 [0.92941176 0.89019608 0.87058824]
 [0.87843137 0.81960784 0.79215686]
 [0.87843137 0.81960784 0.79215686]]


In [4]:
### Downsampling via voxel buckets
downpcd = pcd.voxel_down_sample(voxel_size=0.05)
o3d.visualization.draw_geometries([coord, downpcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])

In [5]:
### Estimated normals (based on convariance analysis "PCA")
### pressing [N] displays the point cloud normals
### we will orient the normals to the camera location
downpcd.orient_normals_towards_camera_location(camera_location)
o3d.visualization.draw_geometries([coord, downpcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])

In [6]:
### Point cloud selection via polygon volume (can be captured from CAD)
print("Load a polygon volume and use it to crop the original point cloud")
vol = o3d.visualization.read_selection_polygon_volume("../../../Open3D/examples/test_data/Crop/cropped.json")

pcd_bound = o3d.geometry.PointCloud()
pcd_bound.points = o3d.utility.Vector3dVector(vol.bounding_polygon)

o3d.visualization.draw_geometries([coord, downpcd, pcd_bound],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])

Load a polygon volume and use it to crop the original point cloud


In [7]:
### Cropping point clouds
chair = vol.crop_point_cloud(pcd)
chair.paint_uniform_color([1, 1, 0])
o3d.visualization.draw_geometries([chair],
                                  zoom=0.7,
                                  front=[0.5439, -0.2333, -0.8060],
                                  lookat=[2.4615, 2.1331, 1.338],
                                  up=[-0.1781, -0.9708, 0.1608])