In [6]:
import open3d as o3d
import numpy as np

camera_location = np.array([0.0, 0.0, 0.0])
coord = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.5, origin=camera_location)

pcd = o3d.io.read_point_cloud("tableAndBox.pcd")
print(pcd)
print(np.asarray(pcd.points))
# o3d.visualization.draw_geometries([pcd])

o3d.visualization.draw_geometries([coord, pcd],
                                  mesh_show_back_face=True,mesh_show_wireframe=True)

PointCloud with 44470 points.
[[ 0.48923299 -0.63281202 -0.36328101]
 [ 0.49217001 -0.62695301 -0.36328101]
 [ 0.502873   -0.62109399 -0.36328101]
 ...
 [ 0.65039098  0.087891    0.053606  ]
 [ 0.175781   -0.26953101 -0.023661  ]
 [ 0.181641   -0.26953101 -0.024979  ]]
